[package]
name = "fwtype"
version = "0.3.5"
edition = "2024"

[dependencies]
clap = "2.33"
unicode-segmentation = "1.12.0"
#unicode-normalization = "0.1.24"

[build-dependencies]
time = { version = "0.3", features = ["macros", "formatting"] }
